### PR TITLE
Structured root folder

### PR DESCRIPTION
**Pull request by r-Dev03**
Altered root/ file structure, moved JavaScript files, CSS files, and any image files into their respective folders within the /Public folder. E.G index.js -> /Public/JS/index.js
Changed all current script and stylesheet links and all IMG src elements to accommodate the new file structure. Everything works as intended. @pacehutt it will not let me mark it as hacktoberfest.
#9

### CODE REVIEW

**Comment by r-Dev03** [comment]
it seems as though in a different PR these files were altered, there should be no issue, however, I do not know how to update my separate branch since it might run into errors due to the file structure change, any ideas @pacehutt?

**Comment by faaiz-space** [comment]
> it seems as though in a different PR these files were altered, there should be no issue, however, I do not know how to update my separate branch since it might run into errors due to the file structure change, any ideas @pacehutt?

Hey @r-Dev03 we advise you to clone the repo again and make a new branch from the main branch then do the changes.

See if the site is working fine or not with the new folder structure...

After that make a PR and we will look into it.

**Comment by r-Dev03** [comment]
I have already confirmed that the current PR'S file changes still allow the site to work fine, however I guess to have it merged I will have to clone it again. Understood

**Comment by faaiz-space** [comment]
> I have already confirmed that the current PR'S file changes still allow the site to work fine, however I guess to have it merged I will have to clone it again. Understood

Is the site working as the current deployment on our gh-pages?

**Comment by r-Dev03** [comment]
Without the recent PR changes yes, but it won't let me test it unless I clone it down again since the CSS file was changed with the old structure, I'll clone it down and redo the changes tonight, as for the hacktoberfest label do you apply that?

**Comment by faaiz-space** [comment]
> Without the recent PR changes yes, but it won't let me test it unless I clone it down again since the CSS file was changed with the old structure, I'll clone it down and redo the changes tonight, as for the hacktoberfest label do you apply that?

Yes then please clone the recent branch and work✅
And yes we will add the label on merging your PR it'll then reflect on your Hacktoberfest Account.

**Pull request closed without merging**
