### PR TITLE
Structured root folder

### PR DESCRIPTION
**Pull request by r-Dev03**
Altered root/ file structure, moved JavaScript files, CSS files, and any image files into their respective folders within the /Public folder. E.G index.js -> /Public/JS/index.js
Changed all current script and stylesheet links and all IMG src elements to accommodate the new file structure. Everything works as intended.

### CODE REVIEW

**Comment by PaceHut** [comment]
Gotcha will review and merge it soon

**Comment by r-Dev03** [comment]
Plan on merging it soon?

**Comment by PaceHut** [comment]
> Plan on merging it soon? If there are any issues let me know

Yes we are waiting for the Hacktoberfest to start... Just some open-source instincts 📸

**Comment by PaceHut** [comment]
> Ahh, I understand, it seems to start in October 1st, should I sign up as well?

Yes everyone should register, in case you are registering then again make a PR on 1st October with Hacktoberfest label so your PR will be counted in the event, 
We will happily merge it after reviewing.🔜

**Comment by r-Dev03** [comment]
Ok, I'll go ahead and make another PR this coming Saturday, October 1st with the label of hacktoberfest, and look forward to seeing it get merged :D

**Comment by faaiz-space** [comment]
> Ok, I'll go ahead and make another PR this coming Saturday, October 1st with the label of hacktoberfest, and look forward to seeing it get merged :D

Make sure that new merges have been done so do checkout again from the main branch✅

**Pull request closed without merging**
